### PR TITLE
Add .icns for proper macOS icon support

### PR DESCRIPTION
**Pull request by jacksongoode**
I think we needed the .icns file

Should close https://github.com/jpochyla/psst/issues/465

### CODE REVIEW

**Comment by jacksongoode** [comment]
@BionicBison05 Could you install Psst with the latest build artifact and let me know if the glitch goes away for you? It seems to have for me.

**Comment by jacksongoode** [comment]
Also need to make sure this didn't mess up any Windows icon things...

**Comment by BionicBison05** [comment]
It's gone for me! Thank you so much for looking into this!

**Comment by jacksongoode** [comment]
@SO9010 Could I ask if you would check if the icon's look all good on Windows? :)

**Comment by SO9010** [comment]
@jacksongoode I will be able to check next week, my windows laptop is not currently with me :/

**Comment by SO9010** [comment]
yeah no issues introduced on windows :P

**Pull request merged**
