### PR TITLE
Show album cover art

### PR DESCRIPTION
**Pull request by jacksongoode**
This allows users to click on the cover art of a currently playing song and see it in higher quality.

### CODE REVIEW

**Comment by jacksongoode** [comment]
@SO9010 Interested in seeing if there are other suggestions. Maybe add a download button on right click? Esc button could trigger it's closing?

**Comment by SO9010** [comment]
I think having a download option would bear TOS sadly.

**Comment by SO9010** [comment]
I will have a better look soon :)

**Comment by jacksongoode** [comment]
> I think having a download option would bear TOS sadly.

I actually don't know if this would be a TOS breach? I can't really find any information on this?

**Comment by kingosticks** [comment]
> > I think having a download option would bear TOS sadly.
> 
> I actually don't know if this would be a TOS breach? I can't really find any information on this?

I think it would be. You are not supposed to store any Spotify content, anything that comes from their API. See [section 4](https://developer.spotify.com/terms#section-iv-restrictions), sub-section 3. There's a specific mention for coverart where they explicitly say it can be *temporarily* cached.

> Local caching. Do not locally cache any Spotify Content, except as strictly necessary to enhance the performance of your SDA and its functionality, and limited to the temporary caching of:
>
>    metadata and cover art; or

Obviously apps like this probably also want to cache audio data, but technically their public API doesn't actually provide that...

**Comment by jacksongoode** [comment]
Specifically, I need some testing around Windows & Linux appearance of the cover art

**Comment by SO9010** [comment]
Having a look on windows now :)

**Comment by SO9010** [comment]
Okay, so on windows, the window size isn't quite the same as the image, so there are borders on the side, which make it look a bit odd. Also, note the fact that the window doesn't have a name. It feels incomplete having a whole window to itself; maybe we could take this as an opportunity to have a mini-player? This could be pretty simple by just adding the controls at the bottom.

Maybe there's a way to have a pop-up that doesn't have a frame, can't move, and disappears when the focus changes. A bit like a right-click menu? 

Also, another thing that is needed is for the image to have rounded corners.

image

**Comment by jacksongoode** [comment]
@SO9010 I believe this now looks proper on Windows.

**Comment by SO9010** [comment]
Checking it out on linux now!

**Comment by SO9010** [comment]
Looks lovely, I really like the fact that you can close it with esc! I think it would be nice if we also had that for the credits window! I submitted a MR.

**Comment by jacksongoode** [comment]
Super, I merged that PR in and I'll merge this!

**Pull request merged**
