### PR TITLE
fix #461: No playlist on psst-gui and failed to read json error

### LINKED ISSUE #461: No playlist on psst-gui and failed to read json error
**Bug description:** There is no playlist  menu.
 
- Error shown on the gui: 
  "failed to read JSON"

- Error shown on the terminal:
ERROR psst_gui::webapi::client] failed to read local tracks: No such file or directory (os error 2)

**To Reproduce**
Simple open the app with ./psst-gui 

**Environment**
 OS: Linux Mint 21

psst-error

### PR DESCRIPTION
**Pull request by nicolasf**
Makes playlist images an optional Vector.

### CODE REVIEW

**Review by Insprill — APPROVED** [review]
LGTM at a glance, Thank you! I can't test this right now, so I'll wait for someone else to sign off before merging.

**Comment by jacksongoode** [comment]
Though I hadn't had this error before, this build does work for me. Was there a way to reproduce it?

**Comment by nicolasf** [comment]
One reproducer for me is having an empty playlist, which I might have created by mistake using Spotify's app.
As Spotify doesn't have any tracks to choose an image it's returning null on "images".

Here's a snippet of the playlists json from Spotify. I've redacted some fields for privacy:

```json
{
      "collaborative": false,
      "description": "",
      "external_urls": {
        "spotify": "https://open.spotify.com/playlist/MY_PLAYLIST_ID"
      },
      "href": "https://api.spotify.com/v1/playlists/MY_PLAYLIST_ID",
      "id": "MY_PLAYLIST_ID",
      "images": null,
      "name": "My Playlist #66",
      "owner": {
        "display_name": "Nicolas",
        "external_urls": {
          "spotify": "https://open.spotify.com/user/MY_USER_ID"
        },
        "href": "https://api.spotify.com/v1/users/MY_USER_ID",
        "id": "MY_USER_ID",
        "type": "user",
        "uri": "spotify:user:MY_USER_ID"
      },
      "primary_color": null,
      "public": true,
      "snapshot_id": "SNAPSHOT_ID",
      "tracks": {
        "href": "https://api.spotify.com/v1/playlists/MY_PLAYLIST_ID/tracks",
        "total": 0
      },
      "type": "playlist",
      "uri": "spotify:playlist:MY_PLAYLIST_ID"
    }
```

**Comment by jacksongoode** [comment]
@nicolasf I can confirm that an empty playlist will trigger this in main and this PR resolves that!

**Pull request merged**
