### PR TITLE
New authentication flow to resolve #515

### LINKED ISSUE #515: User/pass auth flow now unsupported (Spotify API change)
**Describe the bug**
https://github.com/librespot-org/librespot/issues/1308

Spotify just recently made this change within the last couple days. It breaks all 3rd party apps with this login method. This likely means we'll need to rework the authentication flow since we can't use username and passwords. This will need to be addressed immediately.

**To Reproduce**
Clear cache & sign in.

### PR DESCRIPTION
**Pull request by jacksongoode**
This resolves the issue with a new OAuth method largely referencing the work done in librespot https://github.com/librespot-org/librespot/pull/1309. After this username/pass is completely depreciated. I may not have removed all unused references so I'd be happy for reviews and edits.

### CODE REVIEW

**Comment by jacksongoode** [comment]
@Insprill Since this is a big one and high prio, would you have time to look over this and review?

**Comment by jacksongoode** [comment]
@SO9010 Just to check with another person, does this method work for you from this branch?

**Comment by kingosticks** [comment]
By the way, now everyone required is back from holiday we'll hopefully be merging our PR for this. It's currently going through some review. The intention is to publish a librespot-oauth create but when that'll see an actual release, I can't say. I appreciate you might prefer to control your own copy of that code, this is more just a note that the original version is seeing some updates (error handling mostly).

**Comment by SO9010** [comment]
> @SO9010 Just to check with another person, does this method work for you from this branch?

I'll try it out tomorrow!

**Comment by SO9010** [comment]
@jacksongoode This works perfectly for me!!!

**Pull request merged**
