### PR TITLE
Add cmd+h for hide and ctrl+space for pause/resume

### LINKED ISSUE #91: Addition of keyboard controls
On Mac OS hiding with CMD+H and playing/pausing with space bar etc...

### PR DESCRIPTION
**Pull request by JuliDi**
This should fix #91 in parts, but has a little drawback: you need to press ctrl+space to pause/resume the song.
I could not get the application to react to a normal key even without a modifier (i.e. only pressing space or another key when the psst window is open).
If there is a way to achieve this, I'd be happy to make the according changes.

In case #103 should be implemented (ctrl+w sends druid's `command::CLOSE_WINDOW`), I could add that as well.

### CODE REVIEW

**Comment by jpochyla** [comment]
Hi, thanks for the contribution! While the `Cmd+H` shortcut is definitely Mac-specific, `Ctrl+Space` won't work on other platforms, as we omit the application menu on Windows and Linux. Cross-platform keyboard shortcuts would need to be implemented in a custom controller, handling them in one place, or separately in the specific controllers (i.e. pause/resume in the `PlaybackController`).

**Comment by JuliDi** [comment]
The `Ctrl+Space` shortcut should not be in the application menu, I've added it to the `edit` menu. Isn't that visible on all platforms?
See
https://github.com/jpochyla/psst/blob/b01ac00590fd15d913dc6783f2c9ff33a5c28c0d/psst-gui/src/ui/menu.rs#L9-L15

What do you think about adding a "Playback" menu (like the spotify app) where all those controls are collected and assigned a shortcut? Maybe that'd be a better solution.

> (i.e. pause/resume in the `PlaybackController`)

Could you point me to where that would go in the playback controller? I played around with keydown events in there yesterday but couldn't get anything to work.

**Comment by JuliDi** [comment]
Alright, thanks for your help.

I have reverted the changes regarding pause/resume and left only the `cmd+h` part.

>It would go to the Controller::event method, after the command matching stuff. This might be too cryptic and I will definitely get to it myself very soon, so feel free to omit this from the PR.

Okay, I will have a look and see whether I can make it work, and open a new PR if it does.

**Comment by jpochyla** [comment]
Thank you! ❤️

**Pull request merged**
