### PR TITLE
Bump all packages to latest versions

### PR DESCRIPTION
**Pull request by jacksongoode**
So far in my testing, things seem ok! I moved to use the zbus backend for souvlaki which should be a more minimal and correct implementation on Linux.

### CODE REVIEW

**Comment by jacksongoode** [comment]
@SO9010 Would you be able to check this build on Linux and see if there are any obvious behavioral, CPU, memory or etc differences between main?

**Comment by arch-btw** [comment]
I did this manually ever since last week and it works! No issues, it even seems like it's more responsive.

**Comment by jacksongoode** [comment]
@arch-btw What platform are you on just out of curiosity?

**Comment by arch-btw** [comment]
@jacksongoode I use Arch Linux 👍

**Pull request merged**
