### PR TITLE
icons: Switch to conventional track skip icons

### PR DESCRIPTION
**Pull request by jforberg**
Change the track skipping buttons from ⏩, ⏪ to ⏭, ⏮. The shapes are
from the SF Pro font, same as the old icons.

The icons ⏩, ⏪ conventionally denote fast-forward and rewind (seeking
within a single track). By contrast, the icons ⏭, ⏮ denote track
skipping (moving to the next or previous track).

See for instance: https://en.wikipedia.org/wiki/Media_control_symbols#Symbols

### CODE REVIEW

**Comment by jacksongoode** [comment]
Could you post a screenshot of the new svgs?

**Comment by jforberg** [comment]
2022-02-05-105347_1196x152_scrot

**Comment by jpochyla** [comment]
Hi @jforberg, thanks for the contribution! Can you please fill the names of the icons in the comment on top of the respective const? Merging afterwards.

**Comment by jforberg** [comment]
Hi @jpochyla, I updated the icon names as requested

**Pull request merged**
