### PR TITLE
Add darktheme prototype: WIP

### PR DESCRIPTION
**Pull request by JojiiOfficial**
I created a dark-theme implementation prototype. I couldn't come up with an idea how to implement the dark theme for the menu buttons properly, since they are constants and can't be made variables easily. So this is WIP for now. I thought about making dark-theme a feature but tbh I prefer it to be an option which should become a preference in some kind of option/config menu later on.

### CODE REVIEW

**Comment by jpochyla** [comment]
Thanks! Real theming support would indeed require:

- Refactoring all current use of constants from `ui/theme.rs` to env keys.
- Figuring out all the colors etc.
- Implementing custom widget that switches between the themes in a performant manner (i.e. similar to `EnvScope` but caching the env and updating it only when the theme selector from `State` changes).
- Adding it to the config dialog.
- Bonus points: implementing OS-theme retrieval support to `druid-shell`, ideally with some "theme changed" event.

**Comment by florianjr** [comment]
I saw a gist on how to support automatic event-based dark mode switching on macOS. I'll try it tomorrow and write here again :)

**Comment by JojiiOfficial** [comment]
But on MacOS it would not be cross platform. Or what exactly are you talking about?

**Comment by thibautvdv** [comment]
For later on: I prefer using a config file, like [alacritty](https://github.com/alacritty/alacritty) does with YAML, or [Starship](https://github.com/starship/starship) with TOML. This gives more flexibility than environment variables IMO. Just my two cents!

**Comment by JojiiOfficial** [comment]
Yeah a config file sounds good... But for this, as @jpochyla already said, quite some things need to be done first.

**Comment by jpochyla** [comment]
As of 408e8abd47d0933ca1a47c1aebb5c299b940acfe there is a simple dark theme added. More work on colors is needed, it's not very pleasant right now, but it's a start. I'm leaving this issue open, as reacting to (at least Mac) OS theme changes would be really nice to have as well.

Screenshot 2021-01-14 at 19 13 05

**Pull request closed without merging**
