### PR TITLE
chore: Build Windows ICO using ImageMagick

### PR DESCRIPTION
**Pull request by jstarpl**
This PR adds a step to use ImageMagick to build the Windows ICO file.

### CODE REVIEW

**Comment by jpochyla** [comment]
Uuu, thanks a lot @jstarpl! Unfortunately it seems the Windows build is failing on the ICO step (with `magick` not found).

**Comment by jstarpl** [comment]
I'm gonna look into it some more and try to figure out why it can't find ImageMagick.

**Comment by jstarpl** [comment]
I think the problem was that the "desktop" way of setting the PATH across steps is no longer supported. Supposedly, this is how it should be done: https://stackoverflow.com/questions/60169752/how-to-update-the-path-in-a-github-action-workflow-file-for-a-windows-latest-hos . I tried to apply that solution, let's see if it works now.

**Comment by jstarpl** [comment]
Learning PowerShell is fun! `/sarcasm`. I think the correct string should now be written to the PATH GitHub variable.

**Comment by jstarpl** [comment]
Learning by doing. Hopefully now it's correct.

**Comment by jstarpl** [comment]
Okay, the PATH works now, I just missed a line creating a 32-bit 16x16 version.

**Pull request merged**
