### PR TITLE
Remove track from playlist by index

### PR DESCRIPTION
**Pull request by jacksongoode**
Resolves https://github.com/jpochyla/psst/issues/477

### CODE REVIEW

**Comment by jacksongoode** [comment]
@SO9010 Have a look at this, if it seems to work for you we can merge it.

**Comment by SO9010** [comment]
It doesnt seem to work on my end! Also we really need to figure out a way to fix the notifications, because it covers the screen after a bit ahaha!

Here is a screen recording of it:


https://github.com/user-attachments/assets/42ad4227-b0cb-4a61-b2c5-b27e5bdc12d0

In fact observing it more closely it removes the song from the end of the playlist!

**Comment by jacksongoode** [comment]
Oh weird, maybe I messed up. Maybe the index is wrong here, I'm sure this method will work but maybe I'll need to debug.

**Comment by jacksongoode** [comment]
Opps, I think it's working now, misread the API.

**Comment by SO9010** [comment]
Sadly, it still removes all the songs with the same name!

https://github.com/user-attachments/assets/0cf70406-a892-47c8-b379-51d8be8c364e

Sadly I think this is an API issue, perhaps instead we could have a check if someone is adding a song to a playlist, whether that song is already in the playlist then ask the user if they still want to add it a bit like what the official client does? 

It seems like we aren't the only one with this issue
https://community.spotify.com/t5/Spotify-for-Developers/How-delete-one-or-more-elements-from-playlist/td-p/5185630

**Comment by SO9010** [comment]
Or we could do a complex thing where we long the amount of copies there are and their position and just readd them after?

**Comment by kingosticks** [comment]
> Sadly, it still removes all the songs with the same name!
> 2024-07-23.11-46-41.mp4
> 
> Sadly I think this is an API issue, perhaps instead we could have a check if someone is adding a song to a playlist, whether that song is already in the playlist then ask the user if they still want to add it a bit like what the official client does?
> 
> It seems like we aren't the only one with this issue https://community.spotify.com/t5/Spotify-for-Developers/How-delete-one-or-more-elements-from-playlist/td-p/5185630

I think https://community.spotify.com/t5/Spotify-for-Developers/Positions-field-in-JSON-body-is-ignored-when-removing-tracks/td-p/6044424 is more relevent since they recently (silently) broke the API - classic Spotify. Reading that latest thread I think jperez is saying you can still remove by ID but only if you do *not* also specify the track ID. Which is pretty fragile. His de-duplicator app is doing it an entirely different way now.

**Comment by jacksongoode** [comment]
@kingosticks Right, well I think the commit I referenced was made by @jperez on May 8th while that comment was made May 2nd . I would have expected the commit before last to work given that it works for the https://spotify-dedup.com/ project in production... 

https://buymeacoffee.com/jmp/dedup-spotify-breaking-changes-api Makes me think position alone should work - but maybe it needs to be `tracks: positions: []`

**Comment by kingosticks** [comment]
> @kingosticks Right, well I think the commit I referenced was made by @JMPerez on May 8th while that comment was made May 2nd . I would have expected the commit before last to work given that it works for the https://spotify-dedup.com/ project in production...
> 
> https://buymeacoffee.com/jmp/dedup-spotify-breaking-changes-api Makes me think position alone should work - but maybe it needs to be `tracks: positions: []`

Maybe, sorry, I didn't check. But remember: what works today will be silently broken tomorrow. The Spotify API is run by cowboys.

**Comment by jacksongoode** [comment]
Right, I initially thought only positions need to be supplied but so far I've tried:

- `tracks: {uid, positions}`
- `tracks: {uid}, positions`
- `tracks: {positions}`
- `positions`

But done really provide the right removal.

**Comment by jacksongoode** [comment]
I just undid the last commit, as I think the one before that is actually working? At least this seems like the correct behavior?

https://github.com/user-attachments/assets/a95938f8-dba8-44bd-b2d2-a766cf659eca

**Comment by SO9010** [comment]
Yeah I suspect the same thing, is there a way to get the original sort of it? Because isn't the sorting done in app?

**Comment by kingosticks** [comment]
I tried it in the web API console, this example request body works for me.
```
{
   "positions": [0]
} 
```

**Comment by jacksongoode** [comment]
With the last commit we get the tracks original index and carry it with the playlist track - all looks good to me!

**Comment by SO9010** [comment]
All looks good to me!

**Pull request merged**
