### PR TITLE
Cycle through AP if blocked

### PR DESCRIPTION
**Pull request by jacksongoode**
Based on https://github.com/librespot-org/librespot/pull/1345

### CODE REVIEW

**Comment by jacksongoode** [comment]
@SO9010 Would you be able to check this one out? Just need one more pair of eyes on this 👀

**Comment by SO9010** [comment]
@jacksongoode sure thing I'll have a look later today!

**Comment by SO9010** [comment]
Ok so I have built it and checked it out, for some reason it causes an error, the same error that we had before: 
`37680 cpu limit exceeded (core dumped)`. This happens when I try and play a song!

**Comment by SO9010** [comment]
Apart from this it seems to be working!

**Comment by SO9010** [comment]
Oh wait this is behind in commits, it looks good to me!

**Pull request merged**
